### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by andrewjslack** [wiziple/gatsby-plugin-intl#1]
Hi, thanks for sharing this starter.

I have been trying to add a default language route that goes to url.com/* rather than url.com/en/* etc
I managed to get it half working with some ternary expressions but I haven't been able to do it without breaking the language detection in the redirect.js file and I am a bit stumped. Where would be the best place to start with this?

Default route would be a great feature to implement.

**Comment by wiziple** [comment]
Please try a new plugin on the repo. You can change default language with redirect options.
