### ISSUE TITLE
Map language in URL to locale

### ISSUE THREAD

**Issue by audunru** [wiziple/gatsby-plugin-intl#108]
Ran into an issue where we want to use a different path segment in the URL than what the actual locale is. This results in complaints in the browser console about missing locale data.

I'm wondering if this needs to be solved in the config.

Current config:

```
    {
      resolve: `gatsby-plugin-intl`,
      options: {
        path: `${__dirname}/../shared/src/lang`,
        languages: ['en', 'no'],
        defaultLanguage: 'no'
      }
    },
```

Proposal where a language can be an object, with the underlying locale name set to "nb" to fix any Intl locale data errors, but use the URL-friendly "no" in the visible URL.

```
    {
      resolve: `gatsby-plugin-intl`,
      options: {
        path: `${__dirname}/../shared/src/lang`,
        languages: ['en', { locale: 'nb', prefix: 'no' }],
        defaultLanguage: 'no'
      }
    },
```

This would, I believe, also allow you to to have URLs like `/english/some/page` but still use one of the available English locales.

Happy to submit a PR if this is of interest.

EDIT: Updated suggestion to use "prefix" as the option for what to use in the URL instead of my original suggestion of "path"

**Comment by snaegeli** [comment]
We would also be very interested in this. We would like to have `/de/` as URL prefix and `de-CH` as locale for correct formatting of numbers and dates.

**Comment by audunru** [comment]
I've started to work on this.

**Comment by smaniotto** [comment]
Hey @audunru! Any success with this effort? We're having a similar problem with the `pt`<>`br` version of our site. Happy to help with what you've started.

**Comment by smaniotto** [comment]
Ah great, I'm using a fork for the time being, with a quick solution that complies with the options format you've suggested (`{ locale: 'pt', prefix: 'br' }`). But would prefer a more proper/tested solution hehe. Thanks, man!

In case somebody needs: https://github.com/smaniotto/gatsby-plugin-intl/tree/prefixes

**Comment by audunru** [comment]
I've opened up a pull request for this now.
