### ISSUE TITLE
HTML in json translation files

### ISSUE THREAD

**Issue by n1pr3t** [wiziple/gatsby-plugin-intl#13]
Hello! 
Thank you for this great plugin, it helped me a lot! 
Is there a way to use HTML in json translation? For example `"message" : "hello <strong>awesome</strong> world"` will be output like `hello <strong>awesome</strong> world`. And i want it to be like  "hello <strong>awesome</strong> world". Is it possible to achieve?

**Comment by jhoffmcd** [comment]
Hi @n1pr3t, you should be able to use:

https://github.com/formatjs/react-intl/wiki/Components#formattedhtmlmessage

You can import it like this:

`import { FormattedHTMLMessage } from "gatsby-plugin-intl"`

**Comment by wiziple** [comment]
@jhoffmcd Thanks for your answer.
@n1pr3t Let me know if you need more help.
