### ISSUE TITLE
Fork and link this repo?

### ISSUE THREAD

**Issue by artt** [wiziple/gatsby-plugin-intl#170]
This is probably a stupid question, but can someone help me with forking this repo, cloning it to my computer, and have my Gatsby project link to it locally? Hot reloading would be nice too.

I tried cloning, then installing the package's dependencies, and link it, but I got an error saying it's missing `webpack`.

(Tried installing webpack would result in saying `node_modules/react-intl/lib/frontmatter` is missing `react`, and installing `react` results in use hook error when I tried using `useIntl()`.)

**Comment by samajammin** [comment]
@artt I believe all you need to do is reference your fork in your project's package.json.

See https://blaipratdesaba.com/how-to-use-an-npm-node-module-that-has-been-forked-b7dd522fdd08
