### ISSUE TITLE
Huge bundle size

### ISSUE THREAD

**Issue by buz-zard** [wiziple/gatsby-plugin-intl#19]
Hi, I tried to launch your `gatsby-starter-default-intl` demo with added `gatsby-plugin-webpack-bundle-analyzer`. Despite only `languages: ['en', 'ko', 'de'],` being enabled, all of the locales are bundled with the app (this adds quite a significant amount of extra bundle size):

![image](https://user-images.githubusercontent.com/3521740/58701415-7e1d3380-83ab-11e9-955d-4ecd674a8cb4.png)

**Comment by jondavidjohn** [comment]
I built a tool to help you analyze webpack bundles for size regressions, and report them directly to GitHub PRs. It's free for open source, so it might be worth checking out and helpful in this scenario.

[https://packtracker.io](https://packtracker.io/?utm_campaign=links&utm_source=github&utm_medium=issueprcomment)

![image](https://user-images.githubusercontent.com/401520/58719965-8ae35c80-8396-11e9-908d-5c5b1d7b8cbf.png)

**Comment by BowlingX** [comment]
This can be fixed with a `gatsby-node.js` file like this:
I would suggest to have this included based on the languages inside the plugin.

```js
/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/node-apis/
 */

// You can delete this file if you're not using it

const webpack = require('webpack')

exports.onCreateWebpackConfig = ({ actions: { setWebpackConfig } }) => {
  console.log("plugins")
  setWebpackConfig({
    plugins: [
      new webpack.ContextReplacementPlugin(/react-intl[/\\]locale-data$/, /de|en/)
    ]
  })
}

```

**Comment by wiziple** [comment]
@BowlingX Thanks!

This issue should be fixed on the next release.
But you can test by doing `npm install --save gatsby-plugin-intl@beta`
