### ISSUE TITLE
Issue: Links using the `Link` component from this plugin do not reset scroll position for new route.

### ISSUE THREAD

**Issue by rchrdnsh** [wiziple/gatsby-plugin-intl#24]
Hi @wiziple!

I am having this issue where links using the `Link` component from this plugin do not reset scroll position to the top of the next page, but rather persist the scroll position of the current page, which is breaking the usability of the app. I'm thinking it's this plugins `Link` component, because when I use the regular Gatsby `Link` component the new page resets scroll position upon the new route. I am also using `gatsby-plugin-layout` to achieve a single page application where the navigation and certain elements on the page do not reload, to allow for animated route transitions, and a smoother, better user experience. I do not know if maybe the combination of both plugins might be the issue, but in any case, if you have any thoughts as to why this might be happening, please share.

This is the repo, if you have the time or energy to take a look:

https://github.com/arrowgtp/alma

Anyway, thanks again :-)

**Comment by wiziple** [comment]
I don't think the issue is related to the Link component, but can you try to import Link from gatsby and test it?

```javascript
import { Link: GatsbyLink } from "gatsby"

...

<GatsbyLink to="/en/about"/>
```

**Comment by rchrdnsh** [comment]
It's even stranger now...some GatsbyLink routes reset, and some don't, but all of the routes from the Link component from this plugin don't reset...I'll close for now and do more digging.
