### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by anicolaides** [wiziple/gatsby-plugin-intl#28]
Dear @wiziple,

As per Google, [here](https://support.google.com/webmasters/answer/189077), there are 3 ways to indicate the localization of the content of a page; for Gatsby, the Html Tag is used. However, when navigating to a localized page the html lang tag stays the same.

![image](https://user-images.githubusercontent.com/10987574/59412051-4a87d380-8dc5-11e9-8eb5-923e7dd8ee54.png)

I can see that, the showcase page, krashna.nl has achieved this successfully; can this functionality be implemented as a showcase in the **gatsby-starter-default-intl** example?

Best,
Alexandros

**Comment by olegshilov** [comment]
You can get current language from `pageContext` and set lang attribute with `react-helmet`;
`layout.js` in **gatsby-starter-default-intl** might look like:

```jsx
import React from "react";
import Helmet from "react-helmet";

export default ({
  children,
  pageContext: {
    intl: { language }
  }
}) => {
  return (
    <main>
      <Helmet htmlAttributes={{ lang: language }} />
      {children}
    </main>
  );
};
```

i'll create a pr right now

**Comment by anicolaides** [comment]
Looks like property intl of pageContext is undefined.

**Comment by olegshilov** [comment]
> Looks like property intl of pageContext is undefined.

hm. i'll check this.

**Comment by anicolaides** [comment]
@olegshilov No worries! Thanks so much for the PR and the insight!

**Comment by anicolaides** [comment]
I'm closing this one up!

Should #31 be merged, this problem will no longer exist.
