### ISSUE TITLE
Suggestion: Make path to locale.json files optional

### ISSUE THREAD

**Issue by anicolaides** [wiziple/gatsby-plugin-intl#32]
Dear @wiziple,

Would you consider making the language JSON resource path of the plugin optional?; for instance, I source the data, for each page, from markdown files; each .md file contains a title and metaDescription for each page.

This can be achieved by using injectIntl, graphql magic and component props that access the intl property.

What do you guys think?

Best,
Alexandros

**Comment by wiziple** [comment]
This is a simple fix. 😄 
Should be good on the next release.
You can test by installing `npm install --save gatsby-plugin-intl@beta`

**Comment by wiziple** [comment]
published on `gatsby-plugin-intl@0.2.5`
