### ISSUE TITLE
Missing hook-based injection API (useIntl) from react-intl

### ISSUE THREAD

**Issue by darekaze** [wiziple/gatsby-plugin-intl#35]
The [hook approach](https://github.com/formatjs/react-intl/blob/master/docs/API.md#useintl-hook) is much cleaner and enables user to write their own custom hooks. Please consider adding it

**Comment by wiziple** [comment]
will consider it once they release official react-intl@3, closing for now.

**Comment by hudochenkov** [comment]
react-intl@3 was released few weeks ago.
