### ISSUE TITLE
`TypeError: intl is undefined` on 404 page

### ISSUE THREAD

**Issue by stefanfrede** [wiziple/gatsby-plugin-intl#39]
As far as I can tell I have more or less the same setup as the `gatsby-starter-default-intl`, but I get a `TypeError: intl is undefined` on the 404 page (https://postimg.cc/Zv03RQBc).

Here is a link to my repo: https://github.com/stefanfrede/50plus-treff/blob/i18n/src/pages/404.js.

I can't figure out if I forgot something or if I found a bug in the plugin, so every help is much appreciated.

The other pages are working.

**Comment by wiziple** [comment]
Can you try `gatsby-plugin-intl@0.2.6`? Thanks!

**Comment by stefanfrede** [comment]
Fixed!
