### ISSUE TITLE
Is storing of all localized page urls in page data scalable?

### ISSUE THREAD

**Issue by andrejpavlovic** [wiziple/gatsby-plugin-intl#41]
I can't see this plugin scaling well when a site has many pages, since paths to all localized pages are stored in `allSitePage`. This can easily grow to megabytes in size. Am I missing something here?

**Comment by jrestall** [comment]
I agree, this plugin won't scale given the current implementation as each page will need to download a list of all the site's URLs, which could easily be huge given they multiply with each supported language.

@wiziple Is there any way around having the allSitePages in each page's context?

**Comment by wiziple** [comment]
I had to work around to find 404 page because `matchPath` currently has some issues.
https://github.com/gatsbyjs/gatsby/issues/15101

This will be removed as soon as the gatsby team fixes the issue.

**Comment by wiziple** [comment]
this issue has been resolved on gatsby-plugin-intl@0.2.7
