### ISSUE TITLE
Handle possible missing forward slash in url in `changeLocale`

### ISSUE THREAD

**Issue by RikuVan** [wiziple/gatsby-plugin-intl#51]
To ensure language changes work when the url does not contain for forward slash, would it be possible to add a check such as this (seems there is a TODO for this):

```
 if (allSitePage.includes(link) || allSitePage.includes(`${link}/`)) {
    gatsbyNavigate(link)
  } else {
    gatsbyNavigate(`/${language}/`)
  }
```

If you are just starting out with this this plugin it can be a bit of a head-scratcher at first why language changes do not work as intended.

**Comment by wiziple** [comment]
allSitePage array is not used anymore since gatsby team fixed matchPath, thanks!
