### ISSUE TITLE
[enhancement] Add tag to next releases

### ISSUE THREAD

**Issue by talensjr** [wiziple/gatsby-plugin-intl#55]
Hi! First, congrats for your work, I use it and it works really well. I faced an issue to which I made a pull request just to later on realise someone else already did it, which is great!, but it is merged on the versions/0.2.7 branch and I need to use it now, so I installed your package referencing that specific branch. 
It would be cool if you can just add a "next" label (or tag) to that branch, so we can just install it as ```yarn add gatsby-plugin-intl@next```
Thanks!

**Comment by wiziple** [comment]
yeah, i'm doing `@beta`, thanks!
