### ISSUE TITLE
Upgrade to `react-intl@3.x`

### ISSUE THREAD

**Issue by simonwiles** [wiziple/gatsby-plugin-intl#62]
Will it be possible to update this plugin to work with `react-intl@3.x`?  There are some useful new features!

https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md

**Comment by jhoffmcd** [comment]
Note, if you use typescript and have updated your `@types/react-intl` to version `3.0.0` you will not be able to perform a `gatsby build` command without receiving errors:

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't import the named export 'Component' from non EcmaScript module (only default export is available)

File: node_modules/react-intl/dist/components/message.mjs
```

For now I recommend using the previous version until this supports v3:

`yarn add @types/react-intl@2.3.18 -D`
