### ISSUE TITLE
Build is blank

### ISSUE THREAD

**Issue by abflussengel** [wiziple/gatsby-plugin-intl#7]
Hi, thank you for working on this, I have been using this to i18n a Gatbsy site. Everything works in the development server, but when I build, the page is blank.
Viewing the source shows some content but I don't understand why this is happening.

This happens building the `gatsby-starter-default-intl` in your example folder with no changes.

**Comment by wiziple** [comment]
What about the https://gatsby-starter-default-intl.netlify.com ?
This DEMO site is built from the `examples/gatsby-starter-default-intl` folder.

**Comment by abflussengel** [comment]
Hi, thanks for your response, here's what I am doing:

With a fresh checkout of the master branch: 
```
cd examples/gatsby-starter-default-intl/
npm install
gatsby build
```
This is what is built to `public/index.html`:
```
<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><title data-react-helmet="true"></title><link rel="shortcut icon" href="/icons/icon-48x48.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="manifest" href="/manifest.webmanifest"/><meta name="theme-color" content="#663399"/><link rel="apple-touch-icon" sizes="48x48" href="/icons/icon-48x48.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="72x72" href="/icons/icon-72x72.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="96x96" href="/icons/icon-96x96.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="144x144" href="/icons/icon-144x144.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="256x256" href="/icons/icon-256x256.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="384x384" href="/icons/icon-384x384.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png?v=07fab8ad5473f1e15e5f98b64f5d02eda19b8316"/><script src="/socket.io/socket.io.js"></script></head><body><noscript id="gatsby-noscript">This app works best with JavaScript enabled.</noscript><div id="___gatsby"></div><script src="/commons.js"></script></body></html>
```

When I open the index.html in any browser, it renders a blank page.

I do realize you are building the live DEMO site with this code base, but I cannot successfully build the project. Other Gatsby build just fine for me and I've tried building the DEMO on two computers and a variety of browsers. To reiterate, the site works perfectly with the development server. Thoughts?

**Comment by wiziple** [comment]
Did you open the index.html directly from the browser?
You need to run `gatsby serve` instead.

https://www.gatsbyjs.org/docs/quick-start#serve-the-production-build-locally

If not, that's weird.

Just to confirm, https://gatsby-starter-default-intl.netlify.com works right?
Checkout `gratsby-starter-default-intl` branch. This is exactly what I deployed on netlify.

**Comment by LionelZoc** [comment]
i'm having the same issue on my gatby project, sometimes when i build and even sometimes on gatsby develop, i have a blank page on index page (path= /) but if browse to another page of my site it works fine.

the blank page does not come everytime i build so it's really scray when deploying on production.

i don't know if @hannarosenfeld found where his issue was coming from
