### ISSUE TITLE
how to handle reversed locale name (eg. us-en instead of en-us)

### ISSUE THREAD

**Issue by adilhaddaoui** [wiziple/gatsby-plugin-intl#75]
I have a use case where I need to revamp a landing page that was on wordpress to Gatsby which is well reference in Google and all but with a wrong locale name (site.com/us-en/some-route-url) instead of  (site.com/en-us/some-route-url).

The issue is that in my config file if I do 
```
    {
      resolve: `gatsby-plugin-intl`,
      options: {
        path: `${__dirname}/src/intl`,
        languages: [`us-en`, `ma-ar`],
        defaultLanguage: `us-en`,
        redirect: true,
      },
    },
```
it gives error of can't find locale "us-en" in react-inlt/locale-data. and when I just reverse it to 
```
    languages: [`en-us`, `ar-ma`],
```
it works, but I need the first use case of us-en to work to maintain the SEO of the landing page, because changing this will ruin my SEO which I worked for, for years.

How can I achieve this with the plugin please ?

**Comment by jojotjebaby** [comment]
@adilhaddaoui can't you create a 301 redirect from your url containing us-en to the correct one ? 
This should wouldn't impact your SEO that much.

**Comment by adilhaddaoui** [comment]
@jojotjebaby Exactly, I got in touch with an SEO expert recently and proposed to him this problem and he assured that as long as it's only this URL part and it can be handled with a 301 redirect it won't affect the SEO and he only suggested to not forget updating the sitemaps as well.

Well thank you too for mentioning that.
