### ISSUE TITLE
Fails with IntlProvider error when using injectIntl wrapper method

### ISSUE THREAD

**Issue by anicolaides** [wiziple/gatsby-plugin-intl#8]
Dear wiziple,

The plugin worked great up to the point where I wrapped all of my pages with withIntl(...). I was able to get the routing going and all, yet, when I use the injectIntl(...) method around my **class** components and some of my ES6 functional components it breaks.
 
The following error is given:

`[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`

Any ideas? 

Best,
Alexandros

**Comment by wiziple** [comment]
I would appreciate if you provide an example repo.
I think you forgot to add `withIntl` on the page component.

**Comment by wiziple** [comment]
You don't have to use `withIntl` anymore.
Please re-open this if you still have the issue.

**Comment by vercetti11** [comment]
I get the same error. I copied your code into my Gatsby environment and I get the same error. It must be something related to the project set up.

**Comment by vercetti11** [comment]
I copied your code into my Gatsby environment and I get the same error. It must be something related to the project set up.
