### ISSUE TITLE
ContextReplacementPlugin doesn't work due to incorrect replacement path

### ISSUE THREAD

**Issue by artemtam** [wiziple/gatsby-plugin-intl#83]
By default Webpack imports all `@formatjs` localization files, because during the build it doesn't know what exactly the application need. To fix this behavior `ContextReplacementPlugin` is used, though it doesn't work correctly.  

Currently, `gatsby-plugin-intl` imports all the localizations regardless of what languages are set in the config:

![image](https://user-images.githubusercontent.com/5302208/68374470-a1fc5680-014d-11ea-8cce-0cfaa5171e5e.png)

To fix this, in `gatsby-node.js` replace

```
new webpack.ContextReplacementPlugin(
        /react-intl[/\\]locale-data$/,
        regex
),
```

with

```
new webpack.ContextReplacementPlugin(
        /@formatjs[/\\]intl-relativetimeformat[/\\]dist[/\\]locale-data$/,
        regex
),
new webpack.ContextReplacementPlugin(
        /@formatjs[/\\]intl-pluralrules[/\\]dist[/\\]locale-data$/,
        regex
),
```
After the changes the final build looks way better:

![image](https://user-images.githubusercontent.com/5302208/68374799-38c91300-014e-11ea-8041-f1e231043c10.png)

**Comment by artemtam** [comment]
Hey @wiziple I actually think this is quite important. You have 1 MB of unused translations in the example app build, a lot of people use it in production also.

**Comment by wiziple** [comment]
Updated!
Haha thanks for poking me!
Yeah, I had no time to do it, and I'm still using old plugin version on my production 😂
