### ISSUE TITLE
defaultLanguage setting does not work

### ISSUE THREAD

**Issue by musicformellons** [wiziple/gatsby-plugin-intl#91]
I noticed that the value set for defaultLanguage is not picked up in my own project. Also tried in the krashna project and the example project in this repo. Same behavior.

Expected:
When I set in gatsby-config.js following settings:
```   
{
      resolve: `gatsby-plugin-intl`,
      options: {
        // language JSON resource path
        path: `${__dirname}/src/intl`,
        // supported languages
        languages: [`nl`, `en`],
        // language file path
        defaultLanguage: `nl`,
        // option to redirect to `/nl` when connecting `/`
        redirect: true,
      }
    }
```
That when I go to the root ```/``` of the domain that it will redirect to ```/nl/```

Actual:
It redirects to ```/en/```, so ```defaulLanguage``` setting does not work.

**Comment by dsfrederic** [comment]
Same issue here. Maybe it chooses default browser language?

**Comment by jepek** [comment]
Looks like this isn't documented enough. 

When you have `redirect: true` the `gatsby-intl-language` local storage entry is created. Once you switch the language this entry in local storage updates and it is used to redirect with the next visit :)

see https://github.com/wiziple/gatsby-plugin-intl/blob/fdb675fbbdd0557f4cbe16977a85ed0f8b6ac151/src/wrap-page.js#L50
